version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.19.1
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    privileged: true
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Amsterdam
    networks:
     - mqtt
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:2021.9.0
    volumes:
      - hass_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
    depends_on:
      - "zigbee2mqtt"
    networks:
      - hass
      - mqtt
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.12
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mqtt
  telegraf:
    container_name: telegraf
    image: telegraf:1.18.1
    depends_on:
      - "zigbee2mqtt"
    volumes:
      - ./telegraf_pi.conf:/etc/telegraf/telegraf.conf:ro
      - telegraf_data:/telegraf
    restart: always
    networks:
      - mqtt
networks:
  hass:
  mqtt:

volumes:
  hass_data:
  mosquitto_log:
  mosquitto_data:
  mosquitto_config:
  telegraf_data:
