version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.22.2
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - 8080:8080
    restart: always
    privileged: true
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Amsterdam
    networks:
     - mqtt
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:2021.12.5
    volumes:
      - hass_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
    depends_on:
      - "zigbee2mqtt"
    networks:
      - hass
      - mqtt
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.12
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    expose:
      - "1883"
      - "9001"
    networks:
      - mqtt
  telegraf:
    container_name: telegraf
    image: telegraf:1.21.1
    depends_on:
      - "zigbee2mqtt"
    volumes:
      - ./telegraf_pi.conf:/etc/telegraf/telegraf.conf:ro
      - telegraf_data:/telegraf
    restart: always
    networks:
      - mqtt
  telegraf_pihole:
    image: telegraf:1.21.1
    restart: unless-stopped
    hostname: telegraf-pihole
    env_file:
      - telegraf_pihole.env
    networks:
      - telegraf_pihole
    secrets:
      - source: telegraf_pihole_config
        target: /etc/telegraf/telegraf.conf
        uid: 'telegraf'
        gid: 'telegraf'
        mode: 0600
    deploy:
      resources:
        limits:
          memory: 1GB
networks:
  hass:
  mqtt:
  telegraf_pihole:
    name: telegraf_pihole

secrets:
  telegraf_pihole_config:
    file: ./telegraf_pihole.conf
volumes:
  hass_data:
  mosquitto_log:
  mosquitto_data:
  mosquitto_config:
  telegraf_data:
